spring.application.name=kofrinho

# Conexão do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/kofrinho
spring.datasource.username=admin
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração da JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuração de Inicialização do DB
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true